if game.PlaceId == 2753915549 then
    print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")
    print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")
        print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")
    print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")
        print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")        print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")
        print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")    print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")
 print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")
 print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")    print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad") print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad") print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad") print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")
      print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")  print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad") loadstring(game:HttpGet("https://raw.githubusercontent.com/Corrupt2625/Bloxfruits/main/Main.lua"))() print("wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad")
    
end
