if game.PlaceId == 2753915549 then
    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
        "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad" loadstring(game:HttpGet("https://raw.githubusercontent.com/Corrupt2625/Bloxfruits/main/Main.lua"))()    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"    "wadhsahdwgyagdsgaydhwuhduigsasfdegweyfgyuhuhdasgdwhudgyusaggggggggwgadyyuasssssssssddddddwad"
    
end
